import type { LogEntry } from "@/components/ReasoningLog";
import type {
  DemandReport,
  Evidence,
  Gap,
  PlatformAdequacy,
  Reframe,
} from "./types";

interface ExportArgs {
  entries: LogEntry[];
  report: DemandReport | null;
  inputDescription: string;
  generatedAt?: Date;
}

/**
 * Pure function: render a full analysis run as a Markdown document.
 *
 * Pulls data from the live log entries (inputs/outputs/timings/errors for
 * each pipeline step) plus the final DemandReport when available. Handles
 * zero-signal runs by switching the tail section to the empty_reason block
 * instead of the Demand diagnostic + Gaps layout.
 */
export function generateMarkdown({
  entries,
  report,
  inputDescription,
  generatedAt = new Date(),
}: ExportArgs): string {
  const lines: string[] = [];

  // Header
  lines.push("# Demand Scope Analysis");
  lines.push("");
  lines.push(`**Input**: ${inputDescription || "—"}`);
  lines.push(`**Generated**: ${generatedAt.toISOString()}`);
  lines.push(`**Pipeline Steps**: ${entries.length}`);
  lines.push("");

  // Pipeline steps
  entries.forEach((entry, i) => {
    lines.push(renderStep(entry, `${i + 1}`, stepTitle(entry.label)));
    if (entry.children && entry.children.length > 0) {
      entry.children.forEach((child, j) => {
        lines.push(
          renderStep(child, `${i + 1}.${j + 1}`, stepTitle(child.label)),
        );
      });
    }
  });

  // Final analysis
  if (report) {
    lines.push("## Final Analysis");
    lines.push("");
    lines.push(renderAdequacy(report.adequacy));

    if (report.empty_reason) {
      lines.push(renderEmptyReason(report));
    } else {
      lines.push(renderDiagnostic(report));
      lines.push(renderGaps(report.gaps));
    }
  }

  lines.push("---");
  lines.push(
    "_Generated by Demand Scope · https://github.com/harryxu0824-a11y/demand-scope_",
  );
  lines.push("");

  return lines.join("\n");
}

// ---------- helpers ----------

function renderStep(entry: LogEntry, stepNum: string, name: string): string {
  const lines: string[] = [];
  const heading = stepNum.includes(".") ? "###" : "##";
  lines.push(`${heading} Step ${stepNum}: ${name}`);
  lines.push("");
  lines.push(`**Model**: ${entry.model ?? "—"}`);
  lines.push(`**Duration**: ${fmtDuration(entry)}`);
  lines.push(`**Status**: ${entry.status}`);
  lines.push("");

  if (entry.error) {
    lines.push(`**Error**: ${entry.error}`);
    lines.push("");
  }

  if (entry.input !== undefined && entry.input !== null) {
    lines.push(`${heading}# Input`);
    lines.push("");
    lines.push("```json");
    lines.push(stringify(entry.input));
    lines.push("```");
    lines.push("");
  }

  if (entry.output !== undefined && entry.output !== null) {
    lines.push(`${heading}# Output`);
    lines.push("");
    lines.push("```json");
    lines.push(stringify(entry.output));
    lines.push("```");
    lines.push("");
  }

  return lines.join("\n");
}

function renderAdequacy(a: PlatformAdequacy): string {
  const lines: string[] = [];
  lines.push("### Platform Adequacy");
  lines.push("");
  lines.push(`- **Level**: ${a.level}`);
  if (a.headline_summary) {
    lines.push(`- **Summary**: ${a.headline_summary}`);
  }
  if (a.target_audience) {
    lines.push(`- **Target audience**: ${a.target_audience}`);
  }
  if (a.where_audience_actually_is?.length) {
    lines.push(
      `- **Where audience actually is**: ${a.where_audience_actually_is.join(" · ")}`,
    );
  }
  if (a.reddit_fit_rationale) {
    lines.push(`- **Reddit fit rationale**: ${a.reddit_fit_rationale}`);
  }
  if (a.recommended_alternative_sources?.length) {
    lines.push(
      `- **Recommended alternative sources**: ${a.recommended_alternative_sources.join(" · ")}`,
    );
  }
  lines.push("");
  return lines.join("\n");
}

function renderDiagnostic(r: DemandReport): string {
  const lines: string[] = [];
  lines.push("### Demand Diagnostic");
  lines.push("");
  lines.push(`- **Level**: ${r.demand_level}`);
  lines.push(`- **Type**: ${r.demand_type}`);
  if (r.confidence) {
    lines.push(`- **Confidence**: ${r.confidence}`);
  }
  if (r.demand_level_rationale) {
    lines.push(`- **Summary**: ${r.demand_level_rationale}`);
  }
  if (r.demand_type_rationale) {
    lines.push(`- **Type rationale**: ${r.demand_type_rationale}`);
  }
  if (r.low_adequacy_override) {
    lines.push(
      `- **Note**: ran with low platform adequacy — findings are directional, not conclusive.`,
    );
  }
  lines.push("");
  return lines.join("\n");
}

function renderGaps(gaps: Gap[]): string {
  const lines: string[] = [];
  lines.push(`### Gaps (${gaps.length} total)`);
  lines.push("");
  if (gaps.length === 0) {
    lines.push("_No validated gaps surfaced._");
    lines.push("");
    return lines.join("\n");
  }
  gaps.forEach((g, i) => {
    lines.push(`#### Gap ${i + 1}: ${g.description}`);
    lines.push("");
    lines.push(`**Label**: ${g.verdict}`);
    if (g.critic_notes) {
      lines.push(`**Critic rationale**: ${g.critic_notes}`);
    }
    lines.push("");
    if (g.evidence.length > 0) {
      lines.push(`**Evidence** (${g.evidence.length} quote${g.evidence.length !== 1 ? "s" : ""}):`);
      lines.push("");
      g.evidence.forEach((e, j) => {
        const sub = subredditFromPermalink(e.permalink);
        const where = sub ? ` in r/${sub}` : "";
        lines.push(
          `${j + 1}. ${e.author} (score ${e.score})${where}`,
        );
        e.quote
          .split("\n")
          .forEach((ln) => lines.push(`   > ${ln}`));
        if (e.permalink) lines.push(`   [source](${e.permalink})`);
        lines.push("");
      });
    }
  });
  return lines.join("\n");
}

function renderEmptyReason(r: DemandReport): string {
  const lines: string[] = [];
  const label = (r.empty_reason ?? "").replace(/_/g, " ");
  lines.push(`## Zero signal: ${label}`);
  lines.push("");
  const details = r.empty_reason_details ?? {};

  if (r.empty_reason === "no_discussion") {
    const subs = (details.subreddits_searched as string[] | undefined) ?? [];
    const keywords = (details.keywords_tried as string[] | undefined) ?? [];
    lines.push(
      "Reddit returned no discussion on this topic. The audience likely resolves these problems outside public social platforms.",
    );
    lines.push("");
    if (subs.length) {
      lines.push(`- **Subreddits searched**: ${subs.join(", ")}`);
    }
    if (keywords.length) {
      lines.push(`- **Keywords tried**: ${keywords.join(", ")}`);
    }
    lines.push("");
  } else if (r.empty_reason === "search_mismatch") {
    const posts = (details.posts_found as number | undefined) ?? 0;
    const subs = (details.subreddits_searched as string[] | undefined) ?? [];
    lines.push(
      `We harvested ${posts} post${posts !== 1 ? "s" : ""} in the target subreddits, but our analyzer matched zero of them against the reframed problem — a vocabulary or search-query gap.`,
    );
    lines.push("");
    if (subs.length) {
      lines.push(`- **Subreddits searched**: ${subs.join(", ")}`);
    }
    const rephrase = details.user_language_rephrase as string | undefined;
    if (rephrase) {
      lines.push(`- **User-language rephrase**: ${rephrase}`);
    }
    const pains = details.pain_hypotheses as string[] | undefined;
    if (pains?.length) {
      lines.push(`- **Pain hypotheses**:`);
      pains.forEach((p) => lines.push(`  - ${p}`));
    }
    lines.push("");
  } else if (r.empty_reason === "signal_too_weak") {
    const count = (details.analyzer_evidence_count as number | undefined) ?? 0;
    lines.push(
      `The analyzer surfaced ${count} candidate quote${count !== 1 ? "s" : ""}, but the critic and validator rejected all of them. The filters require (1) a real user pain, (2) an attempted solution, (3) willingness to pay or switch.`,
    );
    lines.push("");
    const rejected =
      (details.rejected_quotes as
        | { gap?: string; quotes?: string[]; rejection_reason?: string }[]
        | undefined) ?? [];
    if (rejected.length) {
      lines.push(`**Rejected quotes** (${rejected.length} group${rejected.length !== 1 ? "s" : ""}):`);
      lines.push("");
      rejected.forEach((r, i) => {
        lines.push(`${i + 1}. ${r.gap ?? "(no gap label)"}`);
        (r.quotes ?? []).forEach((q) => lines.push(`   > ${q}`));
        if (r.rejection_reason) {
          lines.push(`   _Why rejected_: ${r.rejection_reason}`);
        }
        lines.push("");
      });
    }
  }
  return lines.join("\n");
}

function stepTitle(label: string): string {
  if (label === "query_planner") return "Planner";
  if (label === "harvester") return "Harvester";
  if (label === "analyzer") return "Analyzer";
  if (label === "critic") return "Critic";
  if (label === "validator") return "Validator";
  return titleCase(label);
}

function titleCase(s: string): string {
  return s.replace(/\b\w/g, (c) => c.toUpperCase());
}

function fmtDuration(entry: LogEntry): string {
  const ms =
    entry.durationMs ??
    (entry.startedAt != null && entry.endedAt != null
      ? entry.endedAt - entry.startedAt
      : null);
  if (ms == null) return "—";
  return `${(ms / 1000).toFixed(1)}s`;
}

function stringify(v: unknown): string {
  try {
    // Always JSON-encode so a raw string input still reads as valid JSON inside
    // the ```json fence (it becomes "the string") instead of an unquoted
    // paragraph that lies about its type.
    return JSON.stringify(v, null, 2);
  } catch {
    return String(v);
  }
}

function subredditFromPermalink(permalink: string | undefined): string | null {
  if (!permalink) return null;
  const m = permalink.match(/\/r\/([^/]+)/i);
  return m ? m[1] : null;
}

export function downloadFilename(
  input: string,
  d = new Date(),
): string {
  const date = d.toISOString().slice(0, 10);
  const slug = slugify(input) || "analysis";
  return `demand-scope-${date}-${slug}.md`;
}

function slugify(text: string): string {
  const first3 = text.trim().split(/\s+/).slice(0, 3).join("-");
  return first3
    .toLowerCase()
    .replace(/[^a-z0-9-]+/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "");
}

// Also export the reframe type in case tests want it; no runtime effect.
export type { Reframe, Evidence };
